export default function Privacy() {
    return (
        <div className="relative py-16 bg-white overflow-hidden">
            <div className="relative px-4 sm:px-6 lg:px-8">
                <div className="text-lg max-w-prose mx-auto">
                    <h1>
                        <span className="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                            Privacy Policy
                        </span>
                    </h1>
                    {/* <p className="mt-8 text-xl text-gray-500 leading-8">
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </p> */}
                </div>
                <div className="mt-6 prose prose-indigo prose-lg text-gray-500 mx-auto">
                    {/* <h2>Definitions</h2> */}
                    <p>
                        This privacy policy applies to the use of the ai writing tool copykitties and any associated services.

                        The ai writing tool is a tool that helps you write better by providing suggestions and feedback based on your writing.

                        This AI Writing Tool does not take user data. All data used is publicly available or generated by the AI itself. None of the data used is personal or could be used to identify an individual.

                        If you have any questions about this privacy policy, please contact us.
                    </p>
                </div>
            </div>
        </div>
    )
}
